// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApdbHxf7qX4pjgxbWr_qvluIUI8oJ9pXg',
    appId: '1:108834765452:web:43017a23e6d09bff3259a9',
    messagingSenderId: '108834765452',
    projectId: 'wsddigiclock',
    authDomain: 'wsddigiclock.firebaseapp.com',
    storageBucket: 'wsddigiclock.firebasestorage.app',
    measurementId: 'G-EVPDWYPN36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Rn12MF-C6Jm_xWxCBQmxCYOsxtKLETM',
    appId: '1:108834765452:android:0cd392e2d0bfaeba3259a9',
    messagingSenderId: '108834765452',
    projectId: 'wsddigiclock',
    storageBucket: 'wsddigiclock.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQNM3RYIjgtjYmUhHWIbdhpq5H0o1BgpA',
    appId: '1:108834765452:ios:bd1f55351be0497a3259a9',
    messagingSenderId: '108834765452',
    projectId: 'wsddigiclock',
    storageBucket: 'wsddigiclock.firebasestorage.app',
    iosBundleId: 'com.example.wsddigiclock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQNM3RYIjgtjYmUhHWIbdhpq5H0o1BgpA',
    appId: '1:108834765452:ios:bd1f55351be0497a3259a9',
    messagingSenderId: '108834765452',
    projectId: 'wsddigiclock',
    storageBucket: 'wsddigiclock.firebasestorage.app',
    iosBundleId: 'com.example.wsddigiclock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApdbHxf7qX4pjgxbWr_qvluIUI8oJ9pXg',
    appId: '1:108834765452:web:fa142b2e3bbd77c83259a9',
    messagingSenderId: '108834765452',
    projectId: 'wsddigiclock',
    authDomain: 'wsddigiclock.firebaseapp.com',
    storageBucket: 'wsddigiclock.firebasestorage.app',
    measurementId: 'G-CHW8CVDCWB',
  );
}
